name: Documentation

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/documentation.yml
      - Sources/SwiftDoc/**.swift

jobs:
  DocumentatonJob:
    runs-on: ubuntu-latest
    steps:
      - uses: fwcd/swift-docc-action@v1
        with:
          target: StudyShare
          output: ./docs
          hosting-base-path: yourproject
          disable-indexing: 'true'
          transform-for-static-hosting: 'true'
